/** Shared between the SSE route and the client — keep it dependency-free. */

export type StepStatus = "pending" | "running" | "done" | "error";

export type TraceStep = {
  id: string;
  /** Agent name shown in the trace, e.g. "Planner" or "Researcher 2". */
  name: string;
  /** Model badge text, e.g. "Gemini 2.5 Flash". */
  model: string;
  /** One-line description of what this agent is doing. */
  description: string;
  /** Pre-written per role — never generated by a model. */
  reason: string;
  status: StepStatus;
};

export type AgentEvent =
  /** Full replacement of the trace list. Sent whenever any step changes. */
  | { type: "trace"; steps: TraceStep[] }
  /** Short status line shown in the chat bubble while the pipeline runs. */
  | { type: "status"; text: string }
  /** A completed agent's visible contribution, shown before the next agent starts. */
  | { type: "agent_output"; label: string; text: string }
  /** Streamed chunk of the final answer. */
  | { type: "delta"; text: string }
  /** Pipeline finished successfully. */
  | { type: "done" }
  /** Fatal error — `message` is safe to show to the visitor. */
  | { type: "error"; message: string };
