import type { TraceStep } from "./agent-types";

/** Dependency-free so both the server pipeline and the Live panel can import it. */

export const MODEL_LABELS = {
  gemini: "Gemini 3.6 Flash",
  groq: "Groq / Llama 3.3 70B",
} as const;

/**
 * Reasons are pre-written per role and never generated by a model — free,
 * instant, and always accurate about the routing decision that was made.
 */
export const REASONS = {
  planner: "Selected for strong reasoning during task planning",
  researcher: "Selected for fast, focused research",
  critic: "Selected for careful review and error checking",
  writer: "Selected for clear, high-quality final writing",
} as const;

export function makeStep(
  id: string,
  name: string,
  model: string,
  description: string,
  reason: string,
): TraceStep {
  return { id, name, model, description, reason, status: "pending" };
}

/** The shape of a run before anything has happened — also the Live panel's idle state. */
export function initialSteps(): TraceStep[] {
  return [
    makeStep(
      "planner",
      "Planner",
      MODEL_LABELS.gemini,
      "Breaking your request into sub-tasks",
      REASONS.planner,
    ),
    makeStep(
      "researcher",
      "Researcher",
      MODEL_LABELS.groq,
      "Gathering and summarizing sources",
      REASONS.researcher,
    ),
    makeStep(
      "critic",
      "Critic",
      MODEL_LABELS.gemini,
      "Checking the draft for gaps",
      REASONS.critic,
    ),
    makeStep(
      "writer",
      "Writer",
      MODEL_LABELS.gemini,
      "Compiling the final answer",
      REASONS.writer,
    ),
  ];
}
